version: '3.9'

services:
  db:
    image: postgres:12
    expose:
      - 5432
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    build: ./server
    command: python3 -m flask run --host=0.0.0.0
    ports:
      - 5000:5000
    env_file: 
      - ./.env
    depends_on:
      - db
    volumes:
      - ./server:/opt/api
  frontend:
    build: ./frontend
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/opt/frontend

volumes:
  postgres_data:
